### ISSUE TITLE
Minify not working

### ISSUE THREAD

**Issue by iezer** [oligriffiths/broccolijs-tutorial#8]
Thanks for the great tutorial @oligriffiths .

I'm trying out step 12 and I can see minification working for CSS but not JS. Is there some additional config needed for uglify? When I say not working I mean there is no difference between the production and development app.js files, and in production that file contains whitespace and long variable names.

Here's the [article](http://www.oligriffiths.com/broccolijs/12-minify.html) and I've confirmed this on [the branch](https://github.com/oligriffiths/broccolijs-tutorial/tree/12-minify).

**Comment by oligriffiths** [comment]
Hmm, i see. Sorry for the slow reply. I wonder why this no longer works. Any ideas?

**Comment by oligriffiths** [comment]
hey @iezer ok I figured it out. The latest version of rollup-plugin-uglify isn't compatible with the published version of broccoli-rollup due to the dependency on an earlier version of Rollup. I've downgraded rollup-plugin-uglify to v3.0.0 for now until broccoli-rollup 1.1.0 is published on npm which does support the latest uglify plugin.
